const state={products:[],mood:"all",query:"",visible:9};
const moodTerms={fresh:["citrus","bergamot","lemon","orange","mint","green","aquatic","fresh","juniper","lavender"],warm:["vanilla","amber","tonka","caramel","honey","warm","spice","benzoin","rum"],bold:["tobacco","leather","oud","smoky","saffron","incense","patchouli","bold"],smooth:["musk","sandalwood","creamy","soft","iris","orris","cedar","smooth"]};
const ui={grid:document.querySelector("#productGrid"),count:document.querySelector("#resultCount"),search:document.querySelector("#searchInput"),clear:document.querySelector("#clearFilters"),loadMore:document.querySelector("#loadMore"),empty:document.querySelector("#emptyState"),dialog:document.querySelector("#scentDialog"),dialogContent:document.querySelector("#dialogContent")};
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function cleanName(name){return name.replace(/\s*[–-]\s*Sample Decant.*$/i,"").trim()}
function firstSentence(text){const sentence=text.replace(/^Overview\s*/i,"").split(/(?<=[.!?])\s+/)[0];return sentence.length>210?`${sentence.slice(0,207)}…`:sentence}
function extractNotes(description){const marker=/(?=\s+(?:Top(?: Notes)?|Heart(?: \(Middle\))?(?: Notes)?|Middle(?: Notes)?|Base(?: Notes)?|Scent Profile|Inspired|Inspiration|Try Before|How it|Why You)|$)/i;const read=label=>description.match(new RegExp(`${label}\\s*:\\s*(.+?)${marker.source}`,"i"))?.[1]?.replace(/[.]$/,"").trim()||"";const groups=[read("Top(?: Notes)?"),read("(?:Heart(?: \\(Middle\\))?|Middle)(?: Notes)?"),read("Base(?: Notes)?")].filter(Boolean);return[...new Set(groups.flatMap(part=>part.split(/,|\band\b|\//i).map(note=>note.trim().replace(/[.]$/,"")).filter(note=>note&&note.length<35)))]}
function inferMood(product){const text=`${product.product_name} ${product.website_description}`.toLowerCase();return Object.entries(moodTerms).map(([mood,terms])=>[mood,terms.filter(term=>text.includes(term)).length]).sort((a,b)=>b[1]-a[1])[0][0]}
function normalizeProduct(raw,id){const notes=extractNotes(raw.website_description||"");const inspiration=(raw.website_vendor||"").replace(/^(?:inspiration|inspired by)\s*:?\s*/i,"");const product={...raw,id,name:cleanName(raw.product_name),notes,inspiration};product.mood=inferMood(product);product.searchable=`${product.name} ${inspiration} ${notes.join(" ")} ${raw.website_description}`.toLowerCase();return product}
function filtered(){const words=state.query.toLowerCase().trim().split(/\s+/).filter(Boolean);return state.products.filter(product=>(state.mood==="all"||moodTerms[state.mood].some(term=>product.searchable.includes(term)))&&words.every(word=>product.searchable.includes(word)))}
function card(product){const noteText=product.notes.slice(0,4).join(" · ")||product.mood;return`<article class="product-card"><button class="card-visual visual-${product.mood}" data-product-id="${product.id}" aria-label="View ${escapeHtml(product.name)}"><span class="card-arrow" aria-hidden="true">↗</span><span class="mini-bottle"><span>${escapeHtml(product.name)}</span></span></button><div class="card-copy"><p class="card-kicker">${product.inspiration?`Inspired by ${escapeHtml(product.inspiration)}`:`${product.mood} profile`}</p><h3>${escapeHtml(product.name)}</h3><p class="card-notes">${escapeHtml(noteText)}</p></div></article>`}
function render(){const matches=filtered();ui.count.textContent=matches.length;ui.grid.innerHTML=matches.slice(0,state.visible).map(card).join("");ui.empty.hidden=matches.length!==0;ui.loadMore.hidden=matches.length<=state.visible;ui.clear.hidden=state.mood==="all"&&!state.query}
function openProduct(id){const product=state.products.find(item=>item.id===Number(id));if(!product)return;const shopUrl=new URL(product.url);shopUrl.searchParams.set("utm_source","scent_finder");shopUrl.searchParams.set("utm_medium","referral");shopUrl.searchParams.set("utm_campaign","product_match");ui.dialogContent.innerHTML=`<div class="dialog-hero visual-${product.mood}"><span class="mini-bottle"><span>${escapeHtml(product.name)}</span></span></div><div class="dialog-body"><p class="card-kicker">${product.inspiration?`Inspired by ${escapeHtml(product.inspiration)}`:`${product.mood} profile`}</p><h2 id="dialogTitle">${escapeHtml(product.name)}</h2><p class="dialog-description">${escapeHtml(firstSentence(product.website_description))}</p><div class="note-list">${product.notes.slice(0,10).map(note=>`<span>${escapeHtml(note)}</span>`).join("")}</div><div class="dialog-actions"><a class="button primary" href="${shopUrl}" target="_blank" rel="noopener">Try a sample at Decantified ↗</a><button class="text-button" data-surprise>Show me another</button></div></div>`;ui.dialog.showModal()}
function clearFilters(){state.mood="all";state.query="";state.visible=9;ui.search.value="";document.querySelectorAll("[data-mood]").forEach(button=>button.classList.toggle("active",button.dataset.mood==="all"));render()}
function surprise(){const pool=filtered().length?filtered():state.products;if(pool.length)openProduct(pool[Math.floor(Math.random()*pool.length)].id)}
document.querySelector("#moodFilters").addEventListener("click",event=>{const button=event.target.closest("[data-mood]");if(!button)return;state.mood=button.dataset.mood;state.visible=9;document.querySelectorAll("[data-mood]").forEach(item=>item.classList.toggle("active",item===button));render()});
ui.search.addEventListener("input",()=>{state.query=ui.search.value;state.visible=9;render()});ui.grid.addEventListener("click",event=>{const item=event.target.closest("[data-product-id]");if(item)openProduct(item.dataset.productId)});ui.loadMore.addEventListener("click",()=>{state.visible+=9;render()});ui.clear.addEventListener("click",clearFilters);document.querySelector("#emptyReset").addEventListener("click",clearFilters);document.querySelector("#surpriseHero").addEventListener("click",surprise);document.querySelector("#dialogClose").addEventListener("click",()=>ui.dialog.close());ui.dialog.addEventListener("click",event=>{if(event.target===ui.dialog)ui.dialog.close();if(event.target.closest("[data-surprise]"))surprise()});
fetch("decantified_product_metadata.json").then(response=>{if(!response.ok)throw Error();return response.json()}).then(products=>{state.products=products.filter(item=>item.fetch_status==="ok"&&item.gender_label!=="women").map(normalizeProduct);render()}).catch(()=>{ui.grid.innerHTML='<p class="dialog-description">The catalog could not be loaded. Please refresh, or browse <a href="https://decantified.com">Decantified.com</a>.</p>';ui.loadMore.hidden=true});
