import { applyCartRules, buildCartUrl, filterProducts, selectBatchVariant, sortVariants, splitNoteTerms } from "./finder-core.js";

const state={catalog:[],bank:{all:[],top:[],heart:[],base:[]},browseMood:"all",browseQuery:"",visible:12,selections:[],rounds:[],activeResults:[],cart:[],exclusions:[],maxPrice:null};
const moods={fresh:["citrus","bergamot","lemon","orange","mint","green","aquatic","fresh","juniper","lavender"],warm:["vanilla","amber","tonka","caramel","honey","warm","spice","benzoin","rum"],bold:["tobacco","leather","oud","smoky","saffron","incense","patchouli","bold"],smooth:["musk","sandalwood","creamy","soft","iris","orris","cedar","smooth"]};
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ui={grid:$("#productGrid"),count:$("#resultCount"),search:$("#searchInput"),finder:$("#finderForm"),noteInput:$("#noteInput"),noteLayer:$("#noteLayer"),selectedNotes:$("#selectedNotes"),popular:$("#popularNotes"),suggestions:$("#noteSuggestions"),similarity:$("#similarityRange"),results:$("#results"),matchGrid:$("#matchGrid"),batch:$("#batchSize"),rounds:$("#roundsList"),dialog:$("#scentDialog"),dialogContent:$("#dialogContent"),cartDialog:$("#cartDialog"),cartItems:$("#cartItems"),toast:$("#toast")};

function hydrate(){try{const saved=JSON.parse(localStorage.getItem("decantified-edit-v1")||"{}");state.cart=Array.isArray(saved.cart)?saved.cart:[];state.exclusions=Array.isArray(saved.exclusions)?saved.exclusions:[];state.maxPrice=saved.maxPrice??null;}catch{localStorage.removeItem("decantified-edit-v1")}}
function persist(){localStorage.setItem("decantified-edit-v1",JSON.stringify({cart:state.cart,exclusions:state.exclusions,maxPrice:state.maxPrice}))}
function inferMood(product){const text=product.searchable;return Object.entries(moods).map(([mood,terms])=>[mood,terms.filter(term=>text.includes(term)).length]).sort((a,b)=>b[1]-a[1])[0][0]}
function normalizeProduct(product){const normalized={...product,id:Number(product.id),notes:[...new Set([product.top,product.heart,product.base].flatMap(splitNoteTerms))]};normalized.searchable=`${product.name} ${product.inspired_by} ${product.top} ${product.heart} ${product.base}`.toLowerCase();normalized.mood=inferMood(normalized);return normalized}
function showToast(message){ui.toast.textContent=message;ui.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.remove("show"),2200)}
function productById(id){return state.catalog.find(product=>product.id===Number(id))}
function visual(product){return `<span class="mini-bottle"><span>${esc(product.name)}</span></span>`}
function card(product,context="browse"){const inCart=state.cart.some(item=>item.productId===product.id);return `<article class="product-card"><button class="card-visual visual-${product.mood}" data-view="${product.id}"><span class="card-arrow">↗</span>${visual(product)}</button><div class="card-copy"><p class="card-kicker">${product.inspired_by?`Inspired by ${esc(product.inspired_by)}`:`${esc(product.gender)} profile`}</p><h3>${esc(product.name)}</h3><p class="card-notes">${esc(product.notes.slice(0,4).join(" · "))}</p><div class="card-meta"><span>From $${esc(product.lowest_in_stock_price)}</span><button class="mini-action ${inCart?"added":""}" data-add="${product.id}" data-context="${context}">${inCart?"In your edit ✓":"Add to edit +"}</button></div></div></article>`}
function browseFiltered(){const words=state.browseQuery.toLowerCase().trim().split(/\s+/).filter(Boolean);return state.catalog.filter(product=>(state.browseMood==="all"||moods[state.browseMood].some(term=>product.searchable.includes(term)))&&words.every(word=>product.searchable.includes(word)))}
function renderBrowse(){const matches=browseFiltered();ui.count.textContent=matches.length;ui.grid.innerHTML=matches.slice(0,state.visible).map(product=>card(product)).join("");$("#emptyState").hidden=matches.length!==0;$("#loadMore").hidden=matches.length<=state.visible;$("#clearFilters").hidden=state.browseMood==="all"&&!state.browseQuery}

function bankForLayer(layer){return state.bank[layer]||[]}
function refreshNoteSuggestions(){const entries=bankForLayer(ui.noteLayer.value);ui.suggestions.innerHTML=entries.slice(0,350).map(entry=>`<option value="${esc(entry.term)}">${entry.count} scents</option>`).join("");ui.popular.innerHTML=entries.slice(0,10).map(entry=>`<button type="button" data-popular="${esc(entry.term)}">${esc(entry.term)} <small>${entry.count}</small></button>`).join("")}
function addSelection(term=ui.noteInput.value){term=term.trim().toLowerCase();if(!term)return showToast("Enter a note first.");const layer=ui.noteLayer.value;const entry=bankForLayer(layer).find(item=>item.term===term);if(!entry)return showToast(`“${term}” is not in the ${layer==="all"?"catalog":layer} note bank.`);if(!state.selections.some(item=>item.layer===layer&&item.term===term))state.selections.push({layer,term});ui.noteInput.value="";renderSelections()}
function renderSelections(){ui.selectedNotes.innerHTML=state.selections.length?state.selections.map((item,index)=>`<button type="button" data-remove-note="${index}"><span>${item.layer==="all"?"Anywhere":item.layer}</span>${esc(item.term)} ×</button>`).join(""):`<p class="muted">No notes selected yet.</p>`}
function resetFinder(){state.selections=[];ui.similarity.value=25;$("#similarityOutput").value="25%";ui.noteLayer.value="all";$("input[name=matchMode][value=any]").checked=true;refreshNoteSuggestions();renderSelections()}
function runSearch(event){event.preventDefault();if(!state.selections.length)return showToast("Add at least one note to search.");const matchMode=$("input[name=matchMode]:checked").value;const maxScore=Number(ui.similarity.value);state.activeResults=filterProducts(state.catalog,state.selections,matchMode,maxScore);const round={id:Date.now(),number:state.rounds.length+1,selections:state.selections.map(item=>({...item})),matchMode,maxScore,resultIds:state.activeResults.map(item=>item.id)};state.rounds.push(round);renderResults(round);renderRounds();ui.results.hidden=false;ui.results.scrollIntoView({behavior:"smooth",block:"start"})}
function resultCard(product){const reasons=product.matches.filter(match=>match.fields.length).map(match=>`${match.term} in ${match.fields.join(", ")}`).join(" · ");return `<article class="match-card"><div class="match-visual visual-${product.mood}" data-view="${product.id}">${visual(product)}<span class="score">${product.similarity.score}% Eau Fraiche</span></div><div><p class="card-kicker">${product.inspired_by?`Inspired by ${esc(product.inspired_by)}`:"Original composition"}</p><h3>${esc(product.name)}</h3><p class="match-reason">Matched ${esc(reasons)}</p><div class="pyramid"><span><b>Top</b>${esc(product.top||"Not listed")}</span><span><b>Heart</b>${esc(product.heart||"Not listed")}</span><span><b>Base</b>${esc(product.base||"Not listed")}</span></div><div class="match-footer"><span>From <b>$${esc(product.lowest_in_stock_price)}</b></span><button class="button secondary compact" data-add="${product.id}" data-context="result">Add to edit +</button></div></div></article>`}
function setBatchOptions(products){const unique=new Map();products.forEach(product=>sortVariants(product.variants).forEach(variant=>unique.set(variant.title.toLowerCase(),variant.title)));const options=[...unique.values()].sort((a,b)=>{const fake={variants:[{title:a,price:"0"},{title:b,price:"0"}]};return sortVariants(fake.variants)[0].title===a?-1:1});ui.batch.innerHTML=options.map((title,index)=>`<option value="${esc(title)}">${esc(title)}${index===0?" (smallest)":""}</option>`).join("")}
function renderResults(round){$("#resultsSummary").textContent=`Round ${round.number}: ${state.activeResults.length} qualifying scents · ${round.matchMode} of ${round.selections.map(item=>item.term).join(", ")} · ≤ ${round.maxScore}% Eau Fraiche similarity`;ui.matchGrid.innerHTML=state.activeResults.map(resultCard).join("");$("#searchEmpty").hidden=state.activeResults.length!==0;setBatchOptions(state.activeResults)}
function renderRounds(){ui.rounds.innerHTML=state.rounds.length?state.rounds.map(round=>`<button type="button" data-round="${round.id}"><span>Round ${round.number}</span><b>${esc(round.selections.map(item=>item.term).join(" + "))}</b><small>${round.resultIds.length} matches · ${round.matchMode}</small></button>`).join(""):`<p class="muted">No searches yet.</p>`}

function addToCart(productId,batchTitle=ui.batch.value){const product=productById(productId);if(!product)return;const existing=state.cart.find(item=>item.productId===product.id);const title=batchTitle||sortVariants(product.variants)[0].title;const {variant,fallback}=selectBatchVariant(product,title);if(existing)existing.variant=variant;else state.cart.push({productId:product.id,variant,searchRounds:state.rounds.filter(round=>round.resultIds.includes(product.id)).map(round=>round.number)});persist();updateCartCount();renderBrowse();if(!ui.results.hidden&&state.rounds.length)renderResults(state.rounds.at(-1));showToast(`${product.name} added${fallback?` in ${variant.title} (smallest fallback)`:""}.`)}
function addAllResults(){if(!state.activeResults.length)return;state.activeResults.forEach(product=>addToCart(product.id,ui.batch.value));showToast(`${state.activeResults.length} matches added to your edit.`)}
function updateCartCount(){$("#cartCount").textContent=state.cart.length}
function setItemVariant(productId,title){const item=state.cart.find(entry=>entry.productId===productId);const product=productById(productId);if(!item||!product)return;item.variant=product.variants.find(variant=>variant.title===title)||item.variant;persist();renderCart()}
function removeCartItem(productId){state.cart=state.cart.filter(item=>item.productId!==productId);persist();updateCartCount();renderCart();renderBrowse()}
function renderCart(){const productsById=new Map(state.catalog.map(product=>[product.id,product]));const rules=applyCartRules(state.cart,productsById,state.exclusions,state.maxPrice);ui.cartItems.innerHTML=state.cart.length?state.cart.map(item=>{const product=productsById.get(item.productId);const removed=rules.removed.find(entry=>entry.productId===item.productId);return `<article class="cart-item ${removed?"rule-removed":""}"><div class="cart-thumb visual-${product.mood}">${visual(product)}</div><div class="cart-item-copy"><h3>${esc(product.name)}</h3><p>${product.inspired_by?`Inspired by ${esc(product.inspired_by)}`:"Original composition"}</p>${removed?`<small>${removed.overPrice?"Above your price limit":`Excluded: ${removed.termHits.map(hit=>hit.term).join(", ")}`}</small>`:""}</div><label>Size<select data-item-size="${product.id}">${sortVariants(product.variants).map(variant=>`<option value="${esc(variant.title)}" ${variant.id===item.variant.id?"selected":""}>${esc(variant.title)} · $${esc(variant.price)}</option>`).join("")}</select></label><button class="remove-item" data-remove-item="${product.id}">Remove</button></article>`}).join(""):`<div class="cart-empty"><b>○</b><h3>Your edit is empty.</h3><p>Run a note search or explore the catalog to add scents.</p></div>`;
  $("#exclusionChips").innerHTML=state.exclusions.map((rule,index)=>`<button data-remove-exclusion="${index}"><span>${rule.exact?"Exact":"Contains"}</span>${esc(rule.term)} ×</button>`).join("");$("#maxPrice").value=state.maxPrice??"";$("#removedSummary").innerHTML=rules.removed.length?`<p><b>${rules.removed.length}</b> item${rules.removed.length===1?"":"s"} removed by your final filters. They remain visible so you can revise the rules.</p>`:"";
  const total=rules.kept.reduce((sum,item)=>sum+Number(item.variant.price||0),0);$("#cartTotal").textContent=`$${total.toFixed(2)}`;$("#cartTotalLabel").textContent=`${rules.kept.length} sample${rules.kept.length===1?"":"s"}`;$("#cartSubhead").textContent=state.cart.length?`${state.cart.length} selected · ${rules.kept.length} ready for cart`:"Add fragrances from any search round.";const link=$("#checkoutLink");const url=buildCartUrl(rules.kept);link.href=url||"#";link.classList.toggle("disabled",!url);link.setAttribute("aria-disabled",String(!url));return rules}
function openCart(){renderCart();ui.cartDialog.showModal()}
function addExclusion(){const term=$("#exclusionInput").value.trim().toLowerCase();if(!term)return;const exact=$("#exclusionMode").value==="exact";if(!state.exclusions.some(rule=>rule.term===term&&rule.exact===exact))state.exclusions.push({term,exact});$("#exclusionInput").value="";persist();renderCart()}
function exportCsv(){const productsById=new Map(state.catalog.map(product=>[product.id,product]));const rules=applyCartRules(state.cart,productsById,state.exclusions,state.maxPrice);const headers=["product_name","url","inspired_by","top","heart","base","gender","eau_fraiche_similarity","cart_selection","variant_id","excluded_from_cart","exclusion_reason","cart_url"];const cartUrl=buildCartUrl(rules.kept);const rows=state.cart.map(item=>{const product=productsById.get(item.productId);const removed=rules.removed.find(entry=>entry.productId===item.productId);return[product.name,product.url,product.inspired_by,product.top,product.heart,product.base,product.gender,product.similarity?.score??"",`${item.variant.title} ($${item.variant.price})`,item.variant.id,removed?"yes":"no",removed?(removed.overPrice?"price limit":removed.termHits.map(hit=>`${hit.term} -> ${hit.fields.join("/")}`).join("; ")):"",removed?"":cartUrl]});const csv=[headers,...rows].map(row=>row.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`decantified-scent-edit-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}

function openProduct(id){const product=productById(id);if(!product)return;const url=new URL(product.url);url.searchParams.set("utm_source","scent_finder");url.searchParams.set("utm_medium","referral");url.searchParams.set("utm_campaign","product_match");ui.dialogContent.innerHTML=`<div class="dialog-hero visual-${product.mood}">${visual(product)}</div><div class="dialog-body"><p class="card-kicker">${product.inspired_by?`Inspired by ${esc(product.inspired_by)}`:"Original composition"}</p><h2 id="dialogTitle">${esc(product.name)}</h2><p class="dialog-description">${esc(product.gender_evidence)}</p><div class="note-pyramid"><div><b>Top</b><p>${esc(product.top||"Not listed")}</p></div><div><b>Heart</b><p>${esc(product.heart||"Not listed")}</p></div><div><b>Base</b><p>${esc(product.base||"Not listed")}</p></div></div><div class="dialog-actions"><button class="button primary" data-add="${product.id}">Add smallest sample · $${esc(sortVariants(product.variants)[0].price)}</button><a class="text-button" href="${url}" target="_blank" rel="noopener">View at Decantified ↗</a></div></div>`;ui.dialog.showModal()}
function surprise(){if(state.catalog.length)openProduct(state.catalog[Math.floor(Math.random()*state.catalog.length)].id)}

document.addEventListener("click",event=>{const view=event.target.closest("[data-view]");if(view)openProduct(view.dataset.view);const add=event.target.closest("[data-add]");if(add)addToCart(Number(add.dataset.add));const removeNote=event.target.closest("[data-remove-note]");if(removeNote){state.selections.splice(Number(removeNote.dataset.removeNote),1);renderSelections()}const popular=event.target.closest("[data-popular]");if(popular)addSelection(popular.dataset.popular);const roundButton=event.target.closest("[data-round]");if(roundButton){const round=state.rounds.find(item=>item.id===Number(roundButton.dataset.round));state.activeResults=round.resultIds.map(productById).map(product=>({...product,...filterProducts([product],round.selections,round.matchMode,round.maxScore)[0]}));renderResults(round);ui.results.hidden=false;ui.results.scrollIntoView({behavior:"smooth"})}});
ui.finder.addEventListener("submit",runSearch);$("#addNote").addEventListener("click",()=>addSelection());ui.noteInput.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();addSelection()}});ui.noteLayer.addEventListener("change",refreshNoteSuggestions);ui.similarity.addEventListener("input",()=>$("#similarityOutput").value=`${ui.similarity.value}%`);$("#resetFinder").addEventListener("click",resetFinder);$("#addAllResults").addEventListener("click",addAllResults);
$("#moodFilters").addEventListener("click",event=>{const button=event.target.closest("[data-mood]");if(!button)return;state.browseMood=button.dataset.mood;state.visible=12;$$('[data-mood]').forEach(item=>item.classList.toggle("active",item===button));renderBrowse()});ui.search.addEventListener("input",()=>{state.browseQuery=ui.search.value;state.visible=12;renderBrowse()});$("#loadMore").addEventListener("click",()=>{state.visible+=12;renderBrowse()});$("#clearFilters").addEventListener("click",()=>{state.browseMood="all";state.browseQuery="";ui.search.value="";$$('[data-mood]').forEach(item=>item.classList.toggle("active",item.dataset.mood==="all"));renderBrowse()});$("#emptyReset").addEventListener("click",()=>$("#clearFilters").click());
$("#openCart").addEventListener("click",openCart);$("[data-close-cart]").addEventListener("click",()=>ui.cartDialog.close());$("[data-close-dialog]").addEventListener("click",()=>ui.dialog.close());$("#addExclusion").addEventListener("click",addExclusion);$("#maxPrice").addEventListener("input",event=>{state.maxPrice=event.target.value===""?null:Math.max(0,Number(event.target.value));persist();renderCart()});ui.cartItems.addEventListener("change",event=>{if(event.target.matches("[data-item-size]"))setItemVariant(Number(event.target.dataset.itemSize),event.target.value)});ui.cartItems.addEventListener("click",event=>{const remove=event.target.closest("[data-remove-item]");if(remove)removeCartItem(Number(remove.dataset.removeItem))});$("#exclusionChips").addEventListener("click",event=>{const button=event.target.closest("[data-remove-exclusion]");if(button){state.exclusions.splice(Number(button.dataset.removeExclusion),1);persist();renderCart()}});$("#exportCsv").addEventListener("click",exportCsv);$("#checkoutLink").addEventListener("click",event=>{if(event.currentTarget.classList.contains("disabled"))event.preventDefault()});$("#surpriseHero").addEventListener("click",surprise);

fetch("web_catalog.json").then(response=>{if(!response.ok)throw Error("Catalog unavailable");return response.json()}).then(data=>{state.catalog=data.products.map(normalizeProduct);state.bank=data.note_bank;hydrate();state.cart=state.cart.filter(item=>productById(item.productId)&&productById(item.productId).variants.some(variant=>variant.id===item.variant.id));$("#catalogTitle").textContent=`Explore all ${state.catalog.length} scents.`;refreshNoteSuggestions();renderSelections();renderBrowse();updateCartCount();persist()}).catch(error=>{console.error(error);ui.grid.innerHTML='<p class="dialog-description">The catalog could not be loaded. Please refresh, or browse <a href="https://decantified.com">Decantified.com</a>.</p>';$("#loadMore").hidden=true});
