import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import {groupFragrances,searchFragrances,buildNoteBank,stockState,chooseVariant,selectionSnapshot,reconcileCart,alternativesFor,migrateCart,checkoutUrl,cartCsv,sortOffers,safeRetailerUrl,newlyListed} from '../catalog-core.js';
const now=Date.parse('2026-09-30T12:00:00Z');
const retailers=new Map([['a',{id:'a',name:'Alpha',origin:'https://a.example',approved_origins:['https://a.example'],adapter:'shopify',checkout_verified_at:'2026-09-30'}],['b',{id:'b',name:'Beta',origin:'https://b.example',approved_origins:['https://b.example'],adapter:'shopify',checkout_verified_at:null}],['decantified',{id:'decantified',name:'Decantified',origin:'https://decantified.com',approved_origins:['https://decantified.com'],adapter:'shopify'}]]);
function offer(id='a',stock='in_stock',currency='USD',size=2){return {id:id+':1',retailer_id:id,fragrance_id:'fragrance:verified',fragrance:{name:'Smoke',brand:'House',concentration:'EDP'},name:'Smoke EDP',url:retailers.get(id).origin+'/products/smoke',top:'Bergamot',heart:'',base:'Vanilla',unlayered:'Honey',observed_at:new Date(now).toISOString(),first_seen_at:new Date(now).toISOString(),initial_import:true,variants:[{id:id+':11',source_id:'11',title:size+'ml',size_ml:size,currency,price_minor:250,stock,observed_at:new Date(now).toISOString()}]};}
const selected=new Set(['a','b']);
test('available default retains fragrance when another retailer sells out',()=>{const a=offer(),b=offer('b','out_of_stock');assert.equal(groupFragrances([b,a],retailers,selected,false,now)[0].offers.length,1);assert.equal(groupFragrances([a,b],retailers,selected,true,now)[0].offers.length,2);assert.equal(groupFragrances([offer('a','out_of_stock'),b],retailers,selected,false,now).length,0);});
test('neutral alphabetic offers and explicit equal-volume currency sorting',()=>{const a=offer(),b=offer('b','in_stock','EUR',5);b.variants[0].price_minor=10;assert.deepEqual(sortOffers([b,a],retailers).map(o=>o.retailer_id),['a','b']);assert.deepEqual(sortOffers([b,a],retailers,{currency:'USD',size_ml:2}).map(o=>o.retailer_id),['a','b']);const registry=JSON.parse(fs.readFileSync(new URL('../retailers.json',import.meta.url)));assert.equal(registry.retailers.length,29);});
test('stock stale, unknown, backorder and discontinued are not available',()=>{const a=offer();assert.equal(stockState(a,a.variants[0],now+73*3600e3),'unknown');for(const stock of ['unknown','backorder','no_longer_listed']){const o=offer('a',stock);assert.equal(chooseVariant(o,2,now).variant,undefined);}a.listing_state='no_longer_listed';assert.equal(stockState(a,a.variants[0],now),'no_longer_listed');});
test('numeric sizes fall back within same retailer',()=>{const a=offer();assert.equal(chooseVariant(a,5,now).variant.id,'a:11');assert.equal(chooseVariant(a,5,now).fallback,true);assert.equal(chooseVariant(a,2,now).fallback,false);});
test('grouped matching keeps evidence and unlayered note behavior',()=>{const a=offer(),b=offer('b');b.top='Lemon';const groups=groupFragrances([a,b],retailers,selected,false,now);const matches=searchFragrances(groups,[{term:'bergamot',layer:'top'},{term:'lemon',layer:'top'}],'all');assert.equal(matches.length,1);assert.equal(matches[0].matches[0].evidence[0].retailerId,'a');assert.ok(buildNoteBank(groups).all.some(e=>e.term==='honey'));assert.equal(searchFragrances(groups,[{term:'honey',layer:'top'}]).length,0);});
test('saved sold-out samples survive and alternatives require verified identity',()=>{const a=offer(),b=offer('b');const saved=selectionSnapshot(a,a.variants[0],retailers.get('a'));a.variants[0].stock='out_of_stock';const offers=new Map([[a.id,a],[b.id,b]]);const item=reconcileCart([saved],offers,retailers,[],{},now)[0];assert.equal(item.ready,false);assert.equal(item.offerId,'a:1');assert.equal(alternativesFor(item,offers,retailers,now)[0].retailer_id,'b');item.snapshot.fragranceId='listing:a:1';item.offer=undefined;assert.equal(alternativesFor(item,offers,retailers,now).length,0);});
test('price reconciliation, missing selections, per-currency ceilings and exclusions',()=>{const a=offer(),saved=selectionSnapshot(a,a.variants[0],retailers.get('a'));a.variants[0].price_minor=300;const offers=new Map([[a.id,a]]);const item=reconcileCart([saved],offers,retailers,[],{EUR:1},now)[0];assert.equal(item.ready,true);assert.equal(item.priceChanged,true);assert.equal(reconcileCart([saved],offers,retailers,[],{USD:299},now)[0].ready,false);assert.equal(reconcileCart([saved],offers,retailers,[{term:'honey',exact:true}],{},now)[0].ready,false);assert.equal(reconcileCart([saved],new Map(),retailers,[],{},now)[0].ready,false);});
test('legacy migration uses variant IDs and preserves price ceiling',()=>{const o=offer('decantified'),offers=new Map([[o.id,o]]);const migrated=migrateCart({cart:[{productId:999,variant:{id:11,price:'1.90'}}],exclusions:[{term:'rose'}],maxPrice:3},offers,retailers);assert.equal(migrated.cart[0].offerId,'decantified:1');assert.equal(migrated.cart[0].snapshot.variant.price_minor,190);assert.equal(migrated.ceilings.USD,300);assert.throws(()=>migrateCart({cart:[{variant:{id:'missing'}}]},offers,retailers));});
test('checkout only verified retailer, ready original variant IDs, safe origins',()=>{const a=offer(),b=offer('b');const items=[a,b].map(o=>({...selectionSnapshot(o,o.variants[0],retailers.get(o.retailer_id)),offer:o,variant:o.variants[0],ready:true,reasons:[],retailer:retailers.get(o.retailer_id),status:'in_stock'}));assert.match(checkoutUrl(items,retailers.get('a')),/a\.example\/cart\/11:1/);assert.equal(checkoutUrl(items,retailers.get('b')),'');assert.equal(safeRetailerUrl('javascript:alert(1)',retailers.get('a')),'');assert.equal(safeRetailerUrl('https://evil.example',retailers.get('a')),'');assert.match(cartCsv(items,retailers),/last_checked/);assert.match(cartCsv(items,retailers),/"Beta"/);});
test('newly listed badge does not label baseline import',()=>{const a=offer();assert.equal(newlyListed(a,now),false);a.initial_import=false;assert.equal(newlyListed(a,now),true);assert.equal(newlyListed(a,now+31*86400e3),false);});
